#!/usr/bin/env sh

# dia:file scripts/log-warn

# ---
# description: >-
#   Logs messages with a warning level designation
# ---

# ---

PRIORITY="3"
DESCRIPTION="WARN"
COLOUR="\033[0;33m"
command -v log-star > /dev/null 2>&1 || {
    printf -- "[ERROR]: log-star not on PATH\n" >&2
    exit 1
}
exec log-star -p "${PRIORITY}" -d "${DESCRIPTION}" -c "${COLOUR}" -- "${@}"
