#!/usr/bin/env sh

# dia:file scripts/log-debug

# ---
# description: >-
#   Logs messages with a debug severity level
# ---

# ---

PRIORITY="1"
DESCRIPTION="DEBUG"
COLOUR="\033[0;34m"
command -v log-star > /dev/null 2>&1 || {
    printf -- "[ERROR]: log-star not on PATH\n" >&2
    exit 1
}
exec log-star -p "${PRIORITY}" -d "${DESCRIPTION}" -c "${COLOUR}" -- "${@}"
